### ISSUE TITLE
WebSocket doesn't accept secure sockets

### ISSUE THREAD

**Issue by rmccue** [Devristo/phpws#56] opened 2015-02-14 09:54 UTC
Right now, the deferred `then` callback in `Client\WebSocket::open` expects a `\React\Stream\Stream` argument. However, when working with secure WebSockets (`wss://`), the argument is instead a `\React\Stream\SecureStream`.

As far as I can see, this should expect a `\React\Stream\DuplexStreamInterface` instead. Any objections to changing this?

**Comment by MRSteam** [comment] 2015-02-19 15:56
wss not work for me too, errors:
"PHP message: PHP Catchable fatal error: Argument 1 passed to Devristo\Phpws\Client\WebSocket::Devristo\Phpws\Client{closure}() must be an instance of React\Stream\Stream, instance of React\SocketClient\SecureStream given, called in /var/www//vendor/react/promise/src/FulfilledPromise.php on line 24 and defined in /var/www//vendor/devristo/phpws/src/Devristo/Phpws/Client/WebSocket.php on line 95" while reading response header from upstream, client: , server: *, request: "GET /api.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: ""

**Comment by clue** [comment] 2015-02-19 16:09
> As far as I can see, this should expect a \React\Stream\DuplexStreamInterface instead. Any objections to changing this?

Changing this to a `DuplexStreamInterface` should fix this, however this is a BC break and requires a dependency on `react/stream: >= 0.4.2, < 0.5.0`. This is caused by a BC break in react/socket-client (https://github.com/reactphp/socket-client/issues/21), suggested fix is in https://github.com/reactphp/socket-client/pull/25.

**Comment by MRSteam** [comment] 2015-02-19 17:04
This works!

**Comment by fatganz** [comment] 2015-03-06 15:12
will that be merged?

**Closed** 2015-03-13 16:18 UTC
